language: csharp
mono: none
dotnet: 3.1.100
solution: CodeWars.sln
before_script:
    - dotnet restore ".\CodeWars\CodeWars.sln"
    
script:
    - dotnet build ".\CodeWars\CodeWars.sln" -c Release
    - dotnet test ".\CodeWars\CodeWars.sln" -c Release -v n
