language: csharp
mono: none
dotnet: 3.1.100
solution: CodeWars.sln
install:
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CodeWars.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
